name: Books Recommended on the Tim Ferriss Show
description: "Fill up your reading list, with books recommended by guests on the Tim Ferriss Show podcast (and Tim himself!)."
author: Ed Shelley
analytics: UA-19619576-14
exclude: [ _design, README ]
baseurl: "/"
